"""Workspace path helpers with cross-platform and traversal-safe boundaries."""

from __future__ import annotations

import re
from pathlib import Path

from .errors import ACSUserError


PROJECT_FILES = {
    "brand": "brand.json",
    "project": "project.json",
    "edit_plan": "edit-plan.json",
}

GENERATED_DIRS = ("renders", "derived", "publish", "reports", "results")


def resolve_project(path: str | Path) -> Path:
    """Resolve a content workspace without requiring it to be under the repo."""

    candidate = Path(path).expanduser().resolve()
    if candidate == candidate.parent:
        raise ACSUserError("Workspace path must be a directory below a filesystem root.")
    return candidate


def project_file(project_dir: Path, key: str) -> Path:
    try:
        filename = PROJECT_FILES[key]
    except KeyError as exc:
        raise ACSUserError(f"Unknown project contract: {key}") from exc
    return project_dir / filename


def safe_relative_path(value: str, *, label: str = "path") -> Path:
    """Return a normalized relative path or fail before it reaches a command."""

    if not isinstance(value, str) or not value.strip():
        raise ACSUserError(f"{label} must be a non-empty relative path.")
    raw = value.replace("\\", "/")
    path = Path(raw)
    if path.is_absolute() or re.match(r"^[A-Za-z]:/", raw):
        raise ACSUserError(f"{label} must stay inside the project: {value!r}")
    if any(part == ".." for part in path.parts):
        raise ACSUserError(f"{label} may not contain '..': {value!r}")
    if path == Path(".") or not path.parts:
        raise ACSUserError(f"{label} must name a file or directory: {value!r}")
    return path


def inside_project(project_dir: Path, relative: str | Path, *, label: str = "path") -> Path:
    path = safe_relative_path(str(relative), label=label)
    resolved = (project_dir / path).resolve()
    try:
        resolved.relative_to(project_dir.resolve())
    except ValueError as exc:
        raise ACSUserError(f"{label} resolves outside the project: {relative!r}") from exc
    return resolved


def render_output_path(project_dir: Path, relative: str | Path, *, label: str = "render output") -> Path:
    """Resolve one active render output strictly beneath ``renders/``.

    Render outputs are generated bytes, not arbitrary workspace paths.  Keep
    this boundary in one helper so active rendering and disabled-output
    pruning cannot accidentally diverge.  Existing symlinks and non-regular
    files are rejected before any caller can hash, replace, or unlink them;
    a missing path is allowed as the destination for a new render.
    """

    path = safe_relative_path(str(relative), label=label)
    renders_candidate = project_dir / "renders"
    if renders_candidate.is_symlink():
        raise ACSUserError("Workspace renders directory may not be a symlink")
    if renders_candidate.exists() and not renders_candidate.is_dir():
        raise ACSUserError("Workspace renders path must be a directory")
    renders_dir = renders_candidate.resolve()
    resolved = (project_dir / path).resolve()
    if resolved == renders_dir:
        raise ACSUserError(f"{label} must name a file below the workspace renders directory")
    try:
        resolved.relative_to(renders_dir)
    except ValueError as exc:
        raise ACSUserError(f"{label} must stay inside the workspace renders directory: {relative!r}") from exc

    candidate = project_dir / path
    ancestor = candidate
    while ancestor != renders_candidate:
        if ancestor.is_symlink():
            raise ACSUserError(f"{label} may not traverse a symlink: {relative!r}")
        if ancestor != candidate and ancestor.exists() and not ancestor.is_dir():
            raise ACSUserError(f"{label} has a non-directory parent: {relative!r}")
        ancestor = ancestor.parent
        if ancestor == project_dir.parent:
            raise ACSUserError(f"{label} must stay inside the workspace renders directory: {relative!r}")
    if candidate.is_symlink():
        raise ACSUserError(f"{label} may not be a symlink: {relative!r}")
    if candidate.exists() and not candidate.is_file():
        raise ACSUserError(f"{label} must be a regular file: {relative!r}")
    return resolved


def display_path(project_dir: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(project_dir.resolve()).as_posix()
    except ValueError:
        return str(path)


def slugify(value: str, fallback: str = "content-project") -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or fallback
